// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs6i-A8aZhzOERb-LbeAnKOXW7KazBjks',
    appId: '1:1078456476988:web:53cf14fd4490a49126aa39',
    messagingSenderId: '1078456476988',
    projectId: 'hotel-booking-1ea32',
    authDomain: 'hotel-booking-1ea32.firebaseapp.com',
    storageBucket: 'hotel-booking-1ea32.firebasestorage.app',
    measurementId: 'G-MGDMZ0BBWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB56rb2Y1S_yrVj4Dh419jg8sIpEDJt72k',
    appId: '1:1078456476988:android:df7d736971ea271d26aa39',
    messagingSenderId: '1078456476988',
    projectId: 'hotel-booking-1ea32',
    storageBucket: 'hotel-booking-1ea32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVWfmN9LmK_75SOJWt7SnsoeSoMXDEpOw',
    appId: '1:1078456476988:ios:59560ae2cc4d3d6126aa39',
    messagingSenderId: '1078456476988',
    projectId: 'hotel-booking-1ea32',
    storageBucket: 'hotel-booking-1ea32.firebasestorage.app',
    iosBundleId: 'com.example.hotelbookingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVWfmN9LmK_75SOJWt7SnsoeSoMXDEpOw',
    appId: '1:1078456476988:ios:59560ae2cc4d3d6126aa39',
    messagingSenderId: '1078456476988',
    projectId: 'hotel-booking-1ea32',
    storageBucket: 'hotel-booking-1ea32.firebasestorage.app',
    iosBundleId: 'com.example.hotelbookingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs6i-A8aZhzOERb-LbeAnKOXW7KazBjks',
    appId: '1:1078456476988:web:ce79efe72a06fdb926aa39',
    messagingSenderId: '1078456476988',
    projectId: 'hotel-booking-1ea32',
    authDomain: 'hotel-booking-1ea32.firebaseapp.com',
    storageBucket: 'hotel-booking-1ea32.firebasestorage.app',
    measurementId: 'G-DP3P1E9HXC',
  );
}
